//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA1231231321.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductsMaterials = new HashSet<ProductsMaterials>();
        }
    
        public string article { get; set; }
        public string title { get; set; }
        public int measure_unit_id { get; set; }
        public int price { get; set; }
        public int max_discount { get; set; }
        public int manufacturer_id { get; set; }
        public int provider_id { get; set; }
        public int category_id { get; set; }
        public int current_discount { get; set; }
        public int count { get; set; }
        public string description { get; set; }
        public string image_path { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual MeasureUnits MeasureUnits { get; set; }
        public virtual Providers Providers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsMaterials> ProductsMaterials { get; set; }
    }
}
